server:
  port: 8400
  
spring:
    datasource:
        url: jdbc:mysql://118.190.202.148:3306/BUPT_IOT?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Gantch815



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:  com.edu.bupt.new_account.model